### ISSUE TITLE
Office for Mac 2011 はこちらへ

### ISSUE THREAD

**Issue by mpyw** [mpyw-yattemita/excel-csv-compatibility-check#1]

**Comment by 39ff** [comment]
```
Shift_JIS.CSV.csv: ◎
Shift_JIS.CSV.tsv: △
Shift_JIS.TSV.csv: ✕
Shift_JIS.TSV.tsv: △
UTF-16_LE.CSV.csv: △
UTF-16_LE.CSV.tsv: △
UTF-16_LE.TSV.csv: ◯
UTF-16_LE.TSV.tsv: ◯
```

**Comment by mpyw** [comment]
あれ…昔使っていた私の記憶では違ったんですが，普通にShift_JISいけます…？

<del>（ちなみに2011と2016は共存インストールできないので注意が必要）</del>

**Comment by mpyw** [comment]
Win/Mac どちらの Excel でも正しく開ける Unicode な csv の出力方法 - Qiita
http://qiita.com/mashiro/items/0d0b9bbb0f4a6cca620c

<del>ここの記事でも暗示されていますが，Shift_JISだと化けた記憶が…
(もしかしてTSVにしていたのだろうか…)</del>

**Comment by 39ff** [comment]
<img width="388" alt="2016-11-08 18 58 35" src="https://cloud.githubusercontent.com/assets/7544687/20094566/32cac178-a5e5-11e6-8b9a-7afa88f34a1c.png">

Shift_JIS.CSV.csv: ◎
<img width="718" alt="2016-11-08 19 26 33" src="https://cloud.githubusercontent.com/assets/7544687/20095506/1229190c-a5e9-11e6-83cb-a37f68f4e6a3.png">

Shift_JIS.CSV.tsv: 元のファイル 日本語 (Mac OS)に変更後区切り文字をコンマに変更して開ける
<img width="538" alt="2016-11-08 19 10 54" src="https://cloud.githubusercontent.com/assets/7544687/20095036/25b88f18-a5e7-11e6-8e7e-ca9cee3b645e.png">
<img width="525" alt="2016-11-08 19 22 59" src="https://cloud.githubusercontent.com/assets/7544687/20095365/8c5349d8-a5e8-11e6-98a4-80c6922a3c7e.png">
<img width="534" alt="2016-11-08 19 28 09" src="https://cloud.githubusercontent.com/assets/7544687/20095563/50f7a342-a5e9-11e6-94ef-7139e1ce200d.png">

<img width="522" alt="2016-11-08 19 21 50" src="https://cloud.githubusercontent.com/assets/7544687/20095318/64ce1df2-a5e8-11e6-9526-0f7ec7e97f61.png">

Shift_JIS.TSV.csv: × 表示が崩れる。
<img width="753" alt="2016-11-08 19 14 29" src="https://cloud.githubusercontent.com/assets/7544687/20095090/61040bb0-a5e7-11e6-898c-7f6ae6bd9b12.png">

Shift_JIS.TSV.tsv: 元のファイル 日本語 (Mac OS)に変更後区切り文字変更せず開ける
<img width="525" alt="2016-11-08 19 16 23" src="https://cloud.githubusercontent.com/assets/7544687/20095149/a591ff76-a5e7-11e6-8b71-25e3a5dbe7a0.png">
<img width="532" alt="2016-11-08 19 18 52" src="https://cloud.githubusercontent.com/assets/7544687/20095253/1b8b3f9e-a5e8-11e6-9cbf-d57c1036b781.png">
<img width="521" alt="2016-11-08 19 20 34" src="https://cloud.githubusercontent.com/assets/7544687/20095275/36169fde-a5e8-11e6-9111-9db2a3cff26a.png">

**Comment by 39ff** [comment]
あと2011と2016の共存は出来てます

![2016-11-08 19 36 29_censored](https://cloud.githubusercontent.com/assets/7544687/20095917/e1d7bcd4-a5ea-11e6-93fd-300459e9d783.jpg)

**Comment by mpyw** [comment]
わざわざ画像ありがとうございます，記憶違いだったみたいですね…
