### ISSUE TITLE
CSV (UTF-8) support is to be added

### ISSUE THREAD

**Issue by chitoku-k** [mpyw-yattemita/excel-csv-compatibility-check#7]
Excel 2016 is now going to add support for CSV files that use UTF-8 in its future release. As I am not one who uses Excel 2016 on Windows I cannot tell you the detail how this works. Furthermore, this update is currently only available for Insiders; however, it is considered to be included in later versions of Excel 2016.

> **CSV (UTF-8) support**
> You can now open and save CSV files that use UTF-8 character encoding. Go to **File** > **Save As** > **Browse**. Then click the **Save as type** menu and you'll find the new option for **CSV UTF-8 (Comma delimited)**. CSV UTF-8 is a commonly used file format that supports more characters than Excel’s existing CSV option (ANSI). What does this mean? Better support for working with non-English data, and ease of moving data to other applications.

Refer to: [What's new in Excel 2016 for Windows - Excel](https://support.office.com/en-us/article/What-s-new-in-Excel-2016-for-Windows-5fdb9208-ff33-45b6-9e08-1f5cdb3a6c73)

**Comment by mpyw** [comment]
What a timely topic! README needs to be updated in the near future.

**Comment by chitoku-k** [comment]
Thanks for your quick addition :+1:

**Comment by chitoku-k** [comment]
It turned out that this update does not have anything to do with compatibility. By the way, I noticed that there seems to be a small misunderstanding in the description of the behavior with how Excel on Windows works, which was fixed in 39a9353. I might have made some mistakes filling the table...
